version: '3.9'
services:
  watersupplynamanger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/?authSource=admin
    networks:
      - apinetwork
  
networks:
  apinetwork:
    name: mongodb-network
    external: true